### Get blogs by tag
GET http://localhost:3001/posts?term=misc

### Get all blogs
GET http://localhost:3001/blogs/

### Post blog
POST http://localhost:3001/blogs/
Content-Type: application/json

{
  "title": "Endpoint Deleted",
  "content": "This content is a test",
  "category": "Testing",
  "tag": "after"
}

### Update a blog
PUT http://localhost:3001/blogs/1
Content-Type: application/json

{
  "title": "PUT NOW",
  "content": "PUT PUT",
  "category": "Testing",
  "tag": "put"
}

### Delete a blog
DELETE http://localhost:3001/blogs/1